version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    restart: always

  ui:
    build:
      context: ./ui
    ports:
      - "4200:4200"
    volumes:
      - ./ui:/app
    working_dir: /app
    restart: always
    depends_on:
      - backend
